Repository Terasology/LightAndShadow, pull requests merged in 2021-12, with the labels that each got.

#242 fix: don't update kill statistics if player died of own account
  src/main/java/org/terasology/module/lightandshadow/systems/PlayerDeathSystem.java
Labels: Type: Bug, Category: Crash, Topic: Stabilization, Status: Needs Testing

#253 feat: add in-game shop in pregame phase
  src/main/java/org/terasology/module/lightandshadow/systems/ClientPregameSystem.java
  src/main/java/org/terasology/module/lightandshadow/systems/ClientStatisticsSystem.java
Labels: Topic: UI/UX, Category: Gameplay Content, Size: S, Type: Improvement

#255 chore: move CombatSystem deltas from LaSR to LaS
  deltas/CombatSystem/prefabs/items/staff.prefab
  deltas/CombatSystem/prefabs/items/sword.prefab
  deltas/CombatSystem/prefabs/items/waraxe.prefab
  deltas/CombatSystem/prefabs/projectiles/fireBall.prefab
  deltas/CombatSystem/prefabs/projectiles/spearThrow.prefab
Labels: Size: S, Topic: Stabilization, Type: Chore
